import mongoose from 'mongoose'
import bcrypt from 'bcryptjs'

// Import models
import Admin from '../models/Admin.js'
import Course from '../models/Course.js'
import Alumni from '../models/Alumni.js'
import Project from '../models/Project.js'
import Team from '../models/Team.js'
import Feature from '../models/Feature.js'
import Statistic from '../models/Statistic.js'
import FAQ from '../models/FAQ.js'
import PageContent from '../models/PageContent.js'
import ContactInfo from '../models/ContactInfo.js'
import SiteSettings from '../models/SiteSettings.js'
import Footer from '../models/Footer.js'
import Certificate from '../models/Certificate.js'

// Demo data
const demoData = {
  admins: [
    {
      name: 'John Admin',
      email: 'admin@techspert.com',
      password: 'admin123456',
      role: 'super-admin',
      profile: {
        bio: 'Super administrator with full system access',
        department: 'IT Administration',
      },
    },
    {
      name: 'Sarah Manager',
      email: 'manager@techspert.com',
      password: 'manager123456',
      role: 'admin',
      profile: {
        bio: 'Content manager responsible for course and project management',
        department: 'Content Management',
      },
    },
    {
      name: 'Mike Moderator',
      email: 'moderator@techspert.com',
      password: 'moderator123456',
      role: 'moderator',
      profile: {
        bio: 'Content moderator for alumni and project approvals',
        department: 'Content Moderation',
      },
    },
  ],

  courses: [
    {
      title: 'Complete MERN Stack Development',
      slug: 'complete-mern-stack-development',
      description: 'Master the MERN stack with hands-on projects and real-world applications. Learn MongoDB, Express.js, React, and Node.js from scratch.',
      shortDescription: 'Build full-stack applications with the MERN stack',
      price: 299,
      originalPrice: 399,
      duration: '12 weeks',
      level: 'intermediate',
      tags: ['MERN', 'Full Stack', 'JavaScript', 'React', 'Node.js'],
      thumbnailUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=500',
      previewUrl: 'https://www.youtube.com/watch?v=example1',
      instructor: {
        name: 'Alex Johnson',
        bio: 'Senior Full Stack Developer with 8+ years experience',
        imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
        socialLinks: {
          linkedin: 'https://linkedin.com/in/alexjohnson',
          github: 'https://github.com/alexjohnson',
        },
      },
      syllabus: [
        {
          title: 'Introduction to MERN Stack',
          description: 'Overview of MongoDB, Express, React, and Node.js',
          duration: '2 hours',
          lessons: 5,
          order: 1,
        },
        {
          title: 'MongoDB Fundamentals',
          description: 'Database design, queries, and relationships',
          duration: '4 hours',
          lessons: 8,
          order: 2,
        },
        {
          title: 'Express.js Backend Development',
          description: 'RESTful APIs, middleware, and authentication',
          duration: '6 hours',
          lessons: 12,
          order: 3,
        },
        {
          title: 'React Frontend Development',
          description: 'Components, state management, and routing',
          duration: '8 hours',
          lessons: 15,
          order: 4,
        },
        {
          title: 'Full Stack Integration',
          description: 'Connecting frontend and backend, deployment',
          duration: '4 hours',
          lessons: 8,
          order: 5,
        },
      ],
      whatYouWillLearn: [
        'Build complete full-stack applications',
        'Implement user authentication and authorization',
        'Create RESTful APIs with Express.js',
        'Design and manage MongoDB databases',
        'Deploy applications to production',
      ],
      requirements: [
        'Basic knowledge of JavaScript',
        'Understanding of HTML and CSS',
        'Node.js installed on your computer',
        'Text editor (VS Code recommended)',
      ],
      isPublished: true,
      isFeatured: true,
      position: 1,
      rating: {
        average: 4.8,
        count: 156,
      },
      studentsCount: 1250,
      completionRate: 87,
    },
    {
      title: 'AI & Machine Learning Fundamentals',
      slug: 'ai-machine-learning-fundamentals',
      description: 'Dive deep into artificial intelligence and machine learning concepts. Learn algorithms, neural networks, and practical applications.',
      shortDescription: 'Master AI and ML concepts with hands-on projects',
      price: 399,
      originalPrice: 499,
      duration: '16 weeks',
      level: 'advanced',
      tags: ['AI', 'Machine Learning', 'Python', 'TensorFlow', 'Neural Networks'],
      thumbnailUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=500',
      previewUrl: 'https://www.youtube.com/watch?v=example2',
      instructor: {
        name: 'Dr. Emily Chen',
        bio: 'AI Research Scientist with PhD in Computer Science',
        imageUrl: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=200',
        socialLinks: {
          linkedin: 'https://linkedin.com/in/emilychen',
          github: 'https://github.com/emilychen',
        },
      },
      syllabus: [
        {
          title: 'Introduction to AI and ML',
          description: 'History, applications, and current trends',
          duration: '3 hours',
          lessons: 6,
          order: 1,
        },
        {
          title: 'Python for Data Science',
          description: 'NumPy, Pandas, and data manipulation',
          duration: '5 hours',
          lessons: 10,
          order: 2,
        },
        {
          title: 'Machine Learning Algorithms',
          description: 'Supervised and unsupervised learning',
          duration: '8 hours',
          lessons: 16,
          order: 3,
        },
        {
          title: 'Deep Learning with TensorFlow',
          description: 'Neural networks and deep learning models',
          duration: '10 hours',
          lessons: 20,
          order: 4,
        },
        {
          title: 'AI Project Development',
          description: 'End-to-end AI project implementation',
          duration: '6 hours',
          lessons: 12,
          order: 5,
        },
      ],
      whatYouWillLearn: [
        'Understand AI and ML fundamentals',
        'Implement machine learning algorithms',
        'Build neural networks with TensorFlow',
        'Create AI-powered applications',
        'Deploy ML models to production',
      ],
      requirements: [
        'Strong programming background',
        'Basic knowledge of Python',
        'Understanding of statistics and mathematics',
        'High-performance computer recommended',
      ],
      isPublished: true,
      isFeatured: true,
      position: 2,
      rating: {
        average: 4.9,
        count: 89,
      },
      studentsCount: 650,
      completionRate: 78,
    },
    {
      title: 'Data Science with Python',
      slug: 'data-science-with-python',
      description: 'Learn data analysis, visualization, and machine learning with Python. Master pandas, matplotlib, and scikit-learn.',
      shortDescription: 'Complete data science journey with Python',
      price: 249,
      originalPrice: 349,
      duration: '10 weeks',
      level: 'intermediate',
      tags: ['Data Science', 'Python', 'Pandas', 'Matplotlib', 'Scikit-learn'],
      thumbnailUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=500',
      previewUrl: 'https://www.youtube.com/watch?v=example3',
      instructor: {
        name: 'Michael Rodriguez',
        bio: 'Data Scientist with 6+ years in analytics and ML',
        imageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200',
        socialLinks: {
          linkedin: 'https://linkedin.com/in/michaelrodriguez',
          github: 'https://github.com/michaelrodriguez',
        },
      },
      syllabus: [
        {
          title: 'Python for Data Analysis',
          description: 'NumPy, Pandas, and data structures',
          duration: '4 hours',
          lessons: 8,
          order: 1,
        },
        {
          title: 'Data Visualization',
          description: 'Matplotlib, Seaborn, and Plotly',
          duration: '3 hours',
          lessons: 6,
          order: 2,
        },
        {
          title: 'Statistical Analysis',
          description: 'Descriptive and inferential statistics',
          duration: '4 hours',
          lessons: 8,
          order: 3,
        },
        {
          title: 'Machine Learning Basics',
          description: 'Scikit-learn and model evaluation',
          duration: '5 hours',
          lessons: 10,
          order: 4,
        },
        {
          title: 'Data Science Project',
          description: 'End-to-end data science project',
          duration: '4 hours',
          lessons: 8,
          order: 5,
        },
      ],
      whatYouWillLearn: [
        'Analyze data with Python libraries',
        'Create compelling data visualizations',
        'Apply statistical methods to data',
        'Build predictive models',
        'Present data insights effectively',
      ],
      requirements: [
        'Basic Python knowledge',
        'Understanding of statistics',
        'Jupyter Notebook experience helpful',
        'Curiosity about data and patterns',
      ],
      isPublished: true,
      isFeatured: false,
      position: 3,
      rating: {
        average: 4.7,
        count: 203,
      },
      studentsCount: 890,
      completionRate: 82,
    },
    {
      title: 'Cloud Computing with AWS',
      slug: 'cloud-computing-with-aws',
      description: 'Master Amazon Web Services and cloud architecture. Learn EC2, S3, Lambda, and deployment strategies.',
      shortDescription: 'Become an AWS cloud expert',
      price: 349,
      originalPrice: 449,
      duration: '14 weeks',
      level: 'intermediate',
      tags: ['AWS', 'Cloud Computing', 'DevOps', 'Infrastructure', 'Deployment'],
      thumbnailUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=500',
      previewUrl: 'https://www.youtube.com/watch?v=example4',
      instructor: {
        name: 'David Kim',
        bio: 'AWS Solutions Architect with 10+ years cloud experience',
        imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
        socialLinks: {
          linkedin: 'https://linkedin.com/in/davidkim',
          github: 'https://github.com/davidkim',
        },
      },
      syllabus: [
        {
          title: 'AWS Fundamentals',
          description: 'Core services and account setup',
          duration: '3 hours',
          lessons: 6,
          order: 1,
        },
        {
          title: 'Compute Services',
          description: 'EC2, Lambda, and container services',
          duration: '5 hours',
          lessons: 10,
          order: 2,
        },
        {
          title: 'Storage and Databases',
          description: 'S3, RDS, and DynamoDB',
          duration: '4 hours',
          lessons: 8,
          order: 3,
        },
        {
          title: 'Networking and Security',
          description: 'VPC, IAM, and security best practices',
          duration: '4 hours',
          lessons: 8,
          order: 4,
        },
        {
          title: 'DevOps and Deployment',
          description: 'CI/CD, monitoring, and automation',
          duration: '4 hours',
          lessons: 8,
          order: 5,
        },
      ],
      whatYouWillLearn: [
        'Design scalable cloud architectures',
        'Deploy applications on AWS',
        'Implement security best practices',
        'Automate infrastructure with DevOps',
        'Optimize costs and performance',
      ],
      requirements: [
        'Basic understanding of networking',
        'Command line experience',
        'AWS free tier account',
        'Linux/Unix familiarity helpful',
      ],
      isPublished: true,
      isFeatured: true,
      position: 4,
      rating: {
        average: 4.6,
        count: 134,
      },
      studentsCount: 720,
      completionRate: 75,
    },
    {
      title: 'Mobile App Development with React Native',
      slug: 'mobile-app-development-react-native',
      description: 'Build cross-platform mobile apps with React Native. Learn navigation, state management, and app store deployment.',
      shortDescription: 'Create iOS and Android apps with React Native',
      price: 279,
      originalPrice: 379,
      duration: '11 weeks',
      level: 'intermediate',
      tags: ['React Native', 'Mobile Development', 'iOS', 'Android', 'JavaScript'],
      thumbnailUrl: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=500',
      previewUrl: 'https://www.youtube.com/watch?v=example5',
      instructor: {
        name: 'Lisa Wang',
        bio: 'Mobile Developer with 7+ years React Native experience',
        imageUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200',
        socialLinks: {
          linkedin: 'https://linkedin.com/in/lisawang',
          github: 'https://github.com/lisawang',
        },
      },
      syllabus: [
        {
          title: 'React Native Basics',
          description: 'Setup, components, and styling',
          duration: '3 hours',
          lessons: 6,
          order: 1,
        },
        {
          title: 'Navigation and Routing',
          description: 'React Navigation and deep linking',
          duration: '3 hours',
          lessons: 6,
          order: 2,
        },
        {
          title: 'State Management',
          description: 'Redux, Context API, and local storage',
          duration: '4 hours',
          lessons: 8,
          order: 3,
        },
        {
          title: 'Native Features',
          description: 'Camera, GPS, push notifications',
          duration: '4 hours',
          lessons: 8,
          order: 4,
        },
        {
          title: 'App Store Deployment',
          description: 'Build, test, and publish apps',
          duration: '3 hours',
          lessons: 6,
          order: 5,
        },
      ],
      whatYouWillLearn: [
        'Build cross-platform mobile apps',
        'Implement navigation and routing',
        'Handle app state management',
        'Access native device features',
        'Deploy to app stores',
      ],
      requirements: [
        'React and JavaScript knowledge',
        'Node.js and npm installed',
        'Android Studio or Xcode',
        'Mobile device for testing',
      ],
      isPublished: true,
      isFeatured: false,
      position: 5,
      rating: {
        average: 4.5,
        count: 98,
      },
      studentsCount: 540,
      completionRate: 80,
    },
  ],

  alumni: [
    {
      name: 'Sarah Johnson',
      title: 'Senior Software Engineer',
      company: 'Google',
      location: 'Mountain View, CA',
      course: 'Complete MERN Stack Development',
      graduationDate: new Date('2023-06-15'),
      imageUrl: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=200',
      testimonial: 'The MERN stack course completely transformed my career. I went from a junior developer to a senior engineer at Google in just 18 months. The hands-on projects and real-world applications made all the difference.',
      socialLinks: {
        linkedin: 'https://linkedin.com/in/sarahjohnson',
        github: 'https://github.com/sarahjohnson',
        twitter: 'https://twitter.com/sarahjohnson',
      },
      email: 'sarah.johnson@google.com',
      skills: ['React', 'Node.js', 'MongoDB', 'JavaScript', 'TypeScript', 'AWS'],
      achievements: [
        {
          title: 'Promoted to Senior Engineer',
          description: 'Promoted within 18 months of joining Google',
          date: new Date('2023-12-01'),
        },
        {
          title: 'Open Source Contributor',
          description: 'Contributed to major React libraries',
          date: new Date('2023-08-15'),
        },
      ],
      isFeatured: true,
      isApproved: true,
      position: 1,
      salary: 180000,
      salaryCurrency: 'USD',
      employmentType: 'full-time',
      yearsOfExperience: 5,
      tags: ['Success Story', 'Career Growth', 'Tech Giant'],
    },
    {
      name: 'Michael Chen',
      title: 'AI Research Scientist',
      company: 'Tesla',
      location: 'Palo Alto, CA',
      course: 'AI & Machine Learning Fundamentals',
      graduationDate: new Date('2023-08-20'),
      imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
      testimonial: 'The AI course gave me the foundation I needed to break into machine learning. Now I\'m working on autonomous vehicle algorithms at Tesla. The instructors were world-class and the projects were challenging.',
      socialLinks: {
        linkedin: 'https://linkedin.com/in/michaelchen',
        github: 'https://github.com/michaelchen',
      },
      email: 'michael.chen@tesla.com',
      skills: ['Python', 'TensorFlow', 'PyTorch', 'Machine Learning', 'Deep Learning', 'Computer Vision'],
      achievements: [
        {
          title: 'Published Research Paper',
          description: 'Co-authored paper on autonomous vehicle perception',
          date: new Date('2024-01-10'),
        },
        {
          title: 'Patent Filed',
          description: 'Filed patent for novel ML algorithm',
          date: new Date('2023-11-15'),
        },
      ],
      isFeatured: true,
      isApproved: true,
      position: 2,
      salary: 220000,
      salaryCurrency: 'USD',
      employmentType: 'full-time',
      yearsOfExperience: 4,
      tags: ['AI Expert', 'Research', 'Innovation'],
    },
    {
      name: 'Emily Rodriguez',
      title: 'Data Science Manager',
      company: 'Netflix',
      location: 'Los Gatos, CA',
      course: 'Data Science with Python',
      graduationDate: new Date('2023-05-10'),
      imageUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200',
      testimonial: 'The data science course was exactly what I needed to transition from marketing to data science. Now I lead a team of data scientists at Netflix, helping improve our recommendation algorithms.',
      socialLinks: {
        linkedin: 'https://linkedin.com/in/emilyrodriguez',
        github: 'https://github.com/emilyrodriguez',
      },
      email: 'emily.rodriguez@netflix.com',
      skills: ['Python', 'Pandas', 'Scikit-learn', 'SQL', 'Statistics', 'Machine Learning'],
      achievements: [
        {
          title: 'Team Leadership',
          description: 'Promoted to manage team of 5 data scientists',
          date: new Date('2023-10-01'),
        },
        {
          title: 'Algorithm Improvement',
          description: 'Improved recommendation accuracy by 15%',
          date: new Date('2023-09-15'),
        },
      ],
      isFeatured: true,
      isApproved: true,
      position: 3,
      salary: 160000,
      salaryCurrency: 'USD',
      employmentType: 'full-time',
      yearsOfExperience: 6,
      tags: ['Leadership', 'Data Science', 'Entertainment Tech'],
    },
    {
      name: 'David Kim',
      title: 'Cloud Solutions Architect',
      company: 'Microsoft',
      location: 'Seattle, WA',
      course: 'Cloud Computing with AWS',
      graduationDate: new Date('2023-07-25'),
      imageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200',
      testimonial: 'The AWS course was comprehensive and practical. I was able to get certified and land a role at Microsoft as a Cloud Solutions Architect. The hands-on labs were incredibly valuable.',
      socialLinks: {
        linkedin: 'https://linkedin.com/in/davidkim',
        github: 'https://github.com/davidkim',
      },
      email: 'david.kim@microsoft.com',
      skills: ['AWS', 'Azure', 'Docker', 'Kubernetes', 'Terraform', 'DevOps'],
      achievements: [
        {
          title: 'AWS Certified',
          description: 'Achieved AWS Solutions Architect Professional certification',
          date: new Date('2023-08-01'),
        },
        {
          title: 'Cost Optimization',
          description: 'Reduced cloud costs by 30% for enterprise clients',
          date: new Date('2023-12-01'),
        },
      ],
      isFeatured: false,
      isApproved: true,
      position: 4,
      salary: 175000,
      salaryCurrency: 'USD',
      employmentType: 'full-time',
      yearsOfExperience: 7,
      tags: ['Cloud Expert', 'Certification', 'Enterprise'],
    },
    {
      name: 'Lisa Wang',
      title: 'Mobile App Developer',
      company: 'Uber',
      location: 'San Francisco, CA',
      course: 'Mobile App Development with React Native',
      graduationDate: new Date('2023-09-15'),
      imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
      testimonial: 'The React Native course was perfect for my career transition. I went from web development to mobile development and now work on the Uber driver app. The course covered everything from basics to deployment.',
      socialLinks: {
        linkedin: 'https://linkedin.com/in/lisawang',
        github: 'https://github.com/lisawang',
      },
      email: 'lisa.wang@uber.com',
      skills: ['React Native', 'iOS', 'Android', 'JavaScript', 'Redux', 'Firebase'],
      achievements: [
        {
          title: 'App Store Success',
          description: 'Published 3 apps with 100k+ downloads',
          date: new Date('2023-11-01'),
        },
        {
          title: 'Performance Optimization',
          description: 'Improved app performance by 40%',
          date: new Date('2023-12-15'),
        },
      ],
      isFeatured: false,
      isApproved: true,
      position: 5,
      salary: 155000,
      salaryCurrency: 'USD',
      employmentType: 'full-time',
      yearsOfExperience: 5,
      tags: ['Mobile Development', 'App Store', 'Performance'],
    },
  ],

  projects: [
    {
      title: 'E-Commerce Platform',
      description: 'A full-stack e-commerce platform built with MERN stack featuring user authentication, payment integration, and admin dashboard.',
      shortDescription: 'Complete e-commerce solution with MERN stack',
      imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=500',
      githubUrl: 'https://github.com/student1/ecommerce-platform',
      liveUrl: 'https://ecommerce-demo.vercel.app',
      technologies: ['React', 'Node.js', 'MongoDB', 'Express', 'Stripe', 'JWT'],
      course: 'Complete MERN Stack Development',
      studentName: 'Alex Thompson',
      studentEmail: 'alex.thompson@email.com',
      completionDate: new Date('2023-12-01'),
      isFeatured: true,
      isApproved: true,
      position: 1,
      views: 1250,
      likes: 89,
      screenshots: [
        {
          url: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800',
          alt: 'E-commerce homepage',
          order: 1,
        },
        {
          url: 'https://images.unsplash.com/photo-1556742111-a301076d9d18?w=800',
          alt: 'Product catalog',
          order: 2,
        },
      ],
      features: [
        'User authentication and authorization',
        'Product catalog with search and filters',
        'Shopping cart and checkout process',
        'Payment integration with Stripe',
        'Admin dashboard for inventory management',
        'Order tracking and history',
      ],
      challenges: [
        'Implementing secure payment processing',
        'Managing complex state in React',
        'Optimizing database queries for performance',
        'Handling file uploads for product images',
      ],
      lessonsLearned: [
        'Importance of proper error handling',
        'Security best practices for web applications',
        'Performance optimization techniques',
        'User experience design principles',
      ],
      tags: ['E-commerce', 'Full Stack', 'Payment Integration'],
    },
    {
      title: 'AI-Powered Chatbot',
      description: 'An intelligent chatbot using natural language processing and machine learning to provide customer support and answer queries.',
      shortDescription: 'Smart chatbot with NLP and ML capabilities',
      imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=500',
      githubUrl: 'https://github.com/student2/ai-chatbot',
      liveUrl: 'https://ai-chatbot-demo.herokuapp.com',
      technologies: ['Python', 'TensorFlow', 'Flask', 'NLTK', 'OpenAI API', 'React'],
      course: 'AI & Machine Learning Fundamentals',
      studentName: 'Maria Garcia',
      studentEmail: 'maria.garcia@email.com',
      completionDate: new Date('2023-11-15'),
      isFeatured: true,
      isApproved: true,
      position: 2,
      views: 980,
      likes: 67,
      screenshots: [
        {
          url: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800',
          alt: 'Chatbot interface',
          order: 1,
        },
        {
          url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
          alt: 'Analytics dashboard',
          order: 2,
        },
      ],
      features: [
        'Natural language understanding',
        'Context-aware conversations',
        'Multi-language support',
        'Analytics and reporting',
        'Integration with external APIs',
        'Customizable responses',
      ],
      challenges: [
        'Training the NLP model effectively',
        'Handling ambiguous user queries',
        'Managing conversation context',
        'Scaling the application for multiple users',
      ],
      lessonsLearned: [
        'Machine learning model optimization',
        'Natural language processing techniques',
        'API integration and management',
        'User interface design for AI applications',
      ],
      tags: ['AI', 'NLP', 'Machine Learning', 'Chatbot'],
    },
    {
      title: 'Data Visualization Dashboard',
      description: 'An interactive dashboard for analyzing and visualizing business data with real-time updates and custom chart configurations.',
      shortDescription: 'Interactive business intelligence dashboard',
      imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=500',
      githubUrl: 'https://github.com/student3/data-dashboard',
      liveUrl: 'https://data-dashboard-demo.netlify.app',
      technologies: ['Python', 'Pandas', 'Plotly', 'Dash', 'PostgreSQL', 'Docker'],
      course: 'Data Science with Python',
      studentName: 'James Wilson',
      studentEmail: 'james.wilson@email.com',
      completionDate: new Date('2023-10-20'),
      isFeatured: false,
      isApproved: true,
      position: 3,
      views: 750,
      likes: 45,
      screenshots: [
        {
          url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
          alt: 'Dashboard overview',
          order: 1,
        },
        {
          url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800',
          alt: 'Chart configurations',
          order: 2,
        },
      ],
      features: [
        'Real-time data updates',
        'Interactive charts and graphs',
        'Custom dashboard layouts',
        'Data export functionality',
        'User authentication',
        'Responsive design',
      ],
      challenges: [
        'Handling large datasets efficiently',
        'Creating responsive visualizations',
        'Implementing real-time updates',
        'Optimizing database queries',
      ],
      lessonsLearned: [
        'Data visualization best practices',
        'Performance optimization for large datasets',
        'User experience in data applications',
        'Database design for analytics',
      ],
      tags: ['Data Visualization', 'Business Intelligence', 'Analytics'],
    },
    {
      title: 'Cloud Infrastructure Manager',
      description: 'A comprehensive tool for managing AWS cloud resources with automated deployment, monitoring, and cost optimization features.',
      shortDescription: 'AWS cloud resource management platform',
      imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=500',
      githubUrl: 'https://github.com/student4/cloud-manager',
      liveUrl: 'https://cloud-manager-demo.aws.amazon.com',
      technologies: ['AWS', 'Terraform', 'Python', 'React', 'Docker', 'Kubernetes'],
      course: 'Cloud Computing with AWS',
      studentName: 'Sarah Davis',
      studentEmail: 'sarah.davis@email.com',
      completionDate: new Date('2023-09-30'),
      isFeatured: true,
      isApproved: true,
      position: 4,
      views: 1100,
      likes: 78,
      screenshots: [
        {
          url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800',
          alt: 'Infrastructure overview',
          order: 1,
        },
        {
          url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800',
          alt: 'Cost analysis',
          order: 2,
        },
      ],
      features: [
        'Automated infrastructure deployment',
        'Real-time monitoring and alerts',
        'Cost optimization recommendations',
        'Resource scaling automation',
        'Security compliance checks',
        'Multi-region deployment support',
      ],
      challenges: [
        'Managing complex AWS permissions',
        'Implementing cost optimization algorithms',
        'Handling multi-region deployments',
        'Ensuring security compliance',
      ],
      lessonsLearned: [
        'Cloud architecture best practices',
        'Infrastructure as Code principles',
        'Cost optimization strategies',
        'Security in cloud environments',
      ],
      tags: ['Cloud Computing', 'AWS', 'DevOps', 'Infrastructure'],
    },
    {
      title: 'Fitness Tracking Mobile App',
      description: 'A cross-platform mobile app for tracking workouts, nutrition, and health metrics with social features and progress analytics.',
      shortDescription: 'Comprehensive fitness tracking mobile app',
      imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500',
      githubUrl: 'https://github.com/student5/fitness-tracker',
      liveUrl: 'https://fitness-tracker-demo.com',
      technologies: ['React Native', 'Firebase', 'Redux', 'Expo', 'Chart.js', 'Push Notifications'],
      course: 'Mobile App Development with React Native',
      studentName: 'Kevin Lee',
      studentEmail: 'kevin.lee@email.com',
      completionDate: new Date('2023-08-25'),
      isFeatured: false,
      isApproved: true,
      position: 5,
      views: 650,
      likes: 52,
      screenshots: [
        {
          url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
          alt: 'Workout tracking',
          order: 1,
        },
        {
          url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
          alt: 'Progress analytics',
          order: 2,
        },
      ],
      features: [
        'Workout tracking and logging',
        'Nutrition and calorie counting',
        'Progress charts and analytics',
        'Social features and challenges',
        'Push notifications and reminders',
        'Offline functionality',
      ],
      challenges: [
        'Implementing offline data sync',
        'Creating smooth animations',
        'Handling device sensors',
        'Managing user privacy and data',
      ],
      lessonsLearned: [
        'Mobile app performance optimization',
        'Cross-platform development challenges',
        'User engagement strategies',
        'Data synchronization techniques',
      ],
      tags: ['Mobile App', 'Health & Fitness', 'React Native', 'Social Features'],
    },
  ],

  team: [
    {
      name: 'Dr. Sarah Johnson',
      role: 'CEO & Founder',
      bio: 'Former Google engineer with 10+ years in tech education. Passionate about democratizing access to quality technology education.',
      imageUrl: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=200',
      email: 'sarah.johnson@techspert.com',
      socialLinks: {
        linkedin: 'https://linkedin.com/in/sarahjohnson',
        twitter: 'https://twitter.com/sarahjohnson',
      },
      department: 'Leadership',
      experience: 12,
      specialties: ['Strategic Planning', 'Tech Education', 'Leadership'],
      isActive: true,
      position: 1,
      isFeatured: true,
    },
    {
      name: 'Michael Chen',
      role: 'Head of AI',
      bio: 'PhD in Machine Learning, former Tesla AI researcher. Expert in deep learning, computer vision, and autonomous systems.',
      imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
      email: 'michael.chen@techspert.com',
      socialLinks: {
        linkedin: 'https://linkedin.com/in/michaelchen',
        github: 'https://github.com/michaelchen',
      },
      department: 'AI & Research',
      experience: 8,
      specialties: ['Machine Learning', 'Deep Learning', 'Computer Vision'],
      isActive: true,
      position: 2,
      isFeatured: true,
    },
    {
      name: 'Emily Rodriguez',
      role: 'Lead Instructor',
      bio: 'Full-stack developer with expertise in MERN stack. Passionate about teaching and helping students build real-world applications.',
      imageUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200',
      email: 'emily.rodriguez@techspert.com',
      socialLinks: {
        linkedin: 'https://linkedin.com/in/emilyrodriguez',
        github: 'https://github.com/emilyrodriguez',
      },
      department: 'Education',
      experience: 6,
      specialties: ['Full Stack Development', 'React', 'Node.js', 'Teaching'],
      isActive: true,
      position: 3,
      isFeatured: true,
    },
    {
      name: 'David Kim',
      role: 'Cloud Solutions Architect',
      bio: 'AWS Solutions Architect with 10+ years cloud experience. Expert in scalable infrastructure and DevOps practices.',
      imageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200',
      email: 'david.kim@techspert.com',
      socialLinks: {
        linkedin: 'https://linkedin.com/in/davidkim',
        github: 'https://github.com/davidkim',
      },
      department: 'Infrastructure',
      experience: 10,
      specialties: ['AWS', 'DevOps', 'Infrastructure', 'Scalability'],
      isActive: true,
      position: 4,
      isFeatured: false,
    },
    {
      name: 'Lisa Wang',
      role: 'Mobile Development Lead',
      bio: 'Mobile Developer with 7+ years React Native experience. Specializes in cross-platform mobile app development.',
      imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
      email: 'lisa.wang@techspert.com',
      socialLinks: {
        linkedin: 'https://linkedin.com/in/lisawang',
        github: 'https://github.com/lisawang',
      },
      department: 'Mobile Development',
      experience: 7,
      specialties: ['React Native', 'iOS', 'Android', 'Mobile UX'],
      isActive: true,
      position: 5,
      isFeatured: false,
    },
  ],

  features: [
    {
      title: 'AI & Machine Learning',
      description: 'Master cutting-edge AI technologies with hands-on projects and real-world applications.',
      icon: 'Brain',
      color: 'from-purple-500 to-pink-500',
      category: 'homepage',
      isActive: true,
      position: 1,
      isFeatured: true,
    },
    {
      title: 'Data Science',
      description: 'Learn data analysis, visualization, and machine learning with industry-standard tools.',
      icon: 'Database',
      color: 'from-blue-500 to-cyan-500',
      category: 'homepage',
      isActive: true,
      position: 2,
      isFeatured: true,
    },
    {
      title: 'MERN Stack',
      description: 'Build full-stack applications with MongoDB, Express, React, and Node.js.',
      icon: 'Code',
      color: 'from-green-500 to-emerald-500',
      category: 'homepage',
      isActive: true,
      position: 3,
      isFeatured: true,
    },
    {
      title: 'Quality Education',
      description: 'We provide high-quality, industry-relevant courses designed by experts.',
      icon: 'Award',
      color: 'from-yellow-500 to-orange-500',
      category: 'about',
      isActive: true,
      position: 1,
      isFeatured: false,
    },
    {
      title: 'Hands-on Learning',
      description: 'Learn by doing with real-world projects and practical exercises.',
      icon: 'Code',
      color: 'from-indigo-500 to-purple-500',
      category: 'about',
      isActive: true,
      position: 2,
      isFeatured: false,
    },
  ],

  statistics: [
    {
      label: 'Students',
      value: '10,000+',
      icon: 'Users',
      category: 'homepage',
      description: 'Active learners worldwide',
      isActive: true,
      position: 1,
      isFeatured: true,
    },
    {
      label: 'Courses',
      value: '50+',
      icon: 'Award',
      category: 'homepage',
      description: 'Comprehensive courses available',
      isActive: true,
      position: 2,
      isFeatured: true,
    },
    {
      label: 'Success Rate',
      value: '95%',
      icon: 'Star',
      category: 'homepage',
      description: 'Students who complete courses',
      isActive: true,
      position: 3,
      isFeatured: true,
    },
    {
      label: 'Projects',
      value: '200+',
      icon: 'Code',
      category: 'homepage',
      description: 'Student projects showcased',
      isActive: true,
      position: 4,
      isFeatured: true,
    },
    {
      label: 'Students Taught',
      value: '10,000+',
      icon: 'Users',
      category: 'about',
      description: 'Successful graduates',
      isActive: true,
      position: 1,
      isFeatured: false,
    },
  ],

  faqs: [
    {
      question: 'How long are the courses?',
      answer: 'Our courses range from 4-12 weeks depending on the complexity and depth of the subject matter. Each course is designed to be comprehensive yet manageable for working professionals.',
      category: 'general',
      isActive: true,
      position: 1,
      isFeatured: true,
      tags: ['duration', 'time', 'schedule'],
    },
    {
      question: 'Do you offer certificates?',
      answer: 'Yes! All our courses come with industry-recognized certificates upon completion. These certificates are verified and can be shared on LinkedIn and other professional platforms.',
      category: 'general',
      isActive: true,
      position: 2,
      isFeatured: true,
      tags: ['certificate', 'completion', 'recognition'],
    },
    {
      question: 'Can I get a refund?',
      answer: 'We offer a 30-day money-back guarantee if you\'re not satisfied with your course. Contact our support team within 30 days of enrollment for a full refund.',
      category: 'billing',
      isActive: true,
      position: 3,
      isFeatured: true,
      tags: ['refund', 'money-back', 'guarantee'],
    },
    {
      question: 'Do you provide job placement assistance?',
      answer: 'Yes, we offer career guidance and job placement assistance to all our students. Our career services include resume review, interview preparation, and connections with hiring partners.',
      category: 'support',
      isActive: true,
      position: 4,
      isFeatured: true,
      tags: ['job', 'placement', 'career', 'assistance'],
    },
    {
      question: 'What if I miss a live session?',
      answer: 'All live sessions are recorded and available for replay. You can access the recordings anytime during the course duration and even after completion.',
      category: 'technical',
      isActive: true,
      position: 5,
      isFeatured: false,
      tags: ['live', 'session', 'recording', 'replay'],
    },
  ],

  pageContent: [
    {
      page: 'home',
      title: 'Master Modern Technology Skills',
      subtitle: 'Join thousands of students learning cutting-edge technologies with our comprehensive courses, hands-on projects, and industry-recognized certificates.',
      description: 'Transform your career with our expert-led courses in AI, data science, full-stack development, and cloud computing.',
      hero: {
        title: 'Master the Future of Technology',
        subtitle: 'Learn cutting-edge skills from industry experts and build your dream career in tech',
        ctaText: 'Start Learning Today',
        backgroundImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=1200',
      },
      sections: {
        features: {
          title: 'Why Choose Techspert?',
          subtitle: 'We provide comprehensive learning experiences designed for real-world success',
        },
        stats: {
          title: 'Our Impact',
          subtitle: 'Join thousands of successful graduates who have transformed their careers',
        },
      },
      seo: {
        metaTitle: 'Techspert - Master Modern Technology Skills',
        metaDescription: 'Learn cutting-edge technologies with expert guidance. Join thousands of successful graduates.',
        keywords: ['technology', 'programming', 'courses', 'online learning', 'tech skills'],
      },
      isActive: true,
    },
    {
      page: 'about',
      title: 'About Techspert',
      subtitle: 'We\'re on a mission to democratize technology education and help people around the world build successful careers in tech.',
      description: 'Learn about our mission, values, and the expert team behind your learning journey.',
      sections: {
        mission: {
          title: 'Our Mission',
          content: 'At Techspert, we believe that everyone should have access to high-quality technology education. Our mission is to bridge the gap between traditional education and industry needs by providing practical, hands-on learning experiences.',
        },
        values: {
          title: 'Our Values',
          subtitle: 'The principles that guide everything we do',
        },
        team: {
          title: 'Meet Our Team',
          subtitle: 'The experts behind your learning journey',
        },
      },
      seo: {
        metaTitle: 'About Techspert - Leading Technology Education',
        metaDescription: 'Learn about our mission to democratize technology education and our expert team.',
        keywords: ['about', 'mission', 'team', 'technology education'],
      },
      isActive: true,
    },
    {
      page: 'contact',
      title: 'Get in Touch',
      subtitle: 'Have questions? We\'d love to hear from you. Send us a message and we\'ll respond as soon as possible.',
      description: 'Contact our team for support, course information, or partnership opportunities.',
      seo: {
        metaTitle: 'Contact Techspert - Get Support and Information',
        metaDescription: 'Get in touch with our team for support, course information, or partnership opportunities.',
        keywords: ['contact', 'support', 'help', 'information'],
      },
      isActive: true,
    },
  ],

  contactInfo: [
    {
      type: 'email',
      title: 'Email Us',
      value: 'contact@techspert.com',
      description: 'Send us an email anytime',
      icon: 'Mail',
      link: 'mailto:contact@techspert.com',
      isActive: true,
      position: 1,
      isPrimary: true,
      category: 'general',
    },
    {
      type: 'phone',
      title: 'Call Us',
      value: '+1 (555) 123-4567',
      description: 'Mon-Fri from 9am to 6pm',
      icon: 'Phone',
      link: 'tel:+15551234567',
      isActive: true,
      position: 2,
      isPrimary: true,
      category: 'general',
    },
    {
      type: 'address',
      title: 'Visit Us',
      value: '123 Tech Street, San Francisco, CA 94105',
      description: 'Come say hello at our office',
      icon: 'MapPin',
      isActive: true,
      position: 3,
      isPrimary: true,
      category: 'general',
    },
    {
      type: 'social',
      title: 'LinkedIn',
      value: 'linkedin.com/company/techspert',
      description: 'Connect with us on LinkedIn',
      icon: 'Linkedin',
      link: 'https://linkedin.com/company/techspert',
      isActive: true,
      position: 4,
      isPrimary: false,
      category: 'general',
    },
    {
      type: 'social',
      title: 'Twitter',
      value: '@techspert',
      description: 'Follow us on Twitter',
      icon: 'Twitter',
      link: 'https://twitter.com/techspert',
      isActive: true,
      position: 5,
      isPrimary: false,
      category: 'general',
    },
  ],

  siteSettings: {
    siteName: 'Techspert',
    siteDescription: 'Learn cutting-edge technology skills with expert guidance',
    siteTagline: 'Empowering the next generation of tech professionals',
    logo: {
      light: '/images/logo-light.png',
      dark: '/images/logo-dark.png',
      favicon: '/images/favicon.ico',
    },
    theme: {
      primary: '#0ea5e9',
      secondary: '#14b8a6',
      accent: '#a855f7',
      background: '#ffffff',
    },
    contact: {
      email: 'contact@techspert.com',
      supportEmail: 'support@techspert.com',
      phone: '+1-555-123-4567',
      address: '123 Tech Street, San Francisco, CA 94105',
    },
    socialMedia: {
      github: 'https://github.com/techspert',
      twitter: 'https://twitter.com/techspert',
      linkedin: 'https://linkedin.com/company/techspert',
      youtube: 'https://youtube.com/techspert',
      instagram: 'https://instagram.com/techspert',
      facebook: 'https://facebook.com/techspert',
    },
    homePage: {
      hero: {
        title: 'Master the Future of Technology',
        subtitle: 'Learn cutting-edge skills from industry experts and build your dream career in tech',
        ctaText: 'Start Learning Today',
        backgroundImage: '/images/hero-bg.jpg',
      },
      features: {
        title: 'Why Choose Techspert?',
        subtitle: 'We provide comprehensive learning experiences designed for real-world success',
      },
      stats: {
        title: 'Our Impact',
        subtitle: 'Join thousands of successful graduates who have transformed their careers',
      },
    },
    seo: {
      metaTitle: 'Techspert - Learn Technology Skills Online',
      metaDescription: 'Master cutting-edge technology skills with expert guidance. Join thousands of successful graduates.',
      keywords: ['technology', 'programming', 'courses', 'online learning', 'tech skills'],
      ogImage: '/images/og-image.jpg',
    },
    analytics: {
      googleAnalyticsId: '',
      googleTagManagerId: '',
      facebookPixelId: '',
    },
    features: {
      enableRegistration: true,
      enableComments: true,
      enableRatings: true,
      enableCertificates: true,
      enableNewsletter: true,
      enableBlog: false,
    },
    maintenance: {
      enabled: false,
      message: 'We are currently performing maintenance. Please check back soon.',
    },
    version: 1,
  },
  footer: {
    brand: {
      name: 'Techspert',
      description: 'Empowering the next generation of developers with cutting-edge technology courses and hands-on projects.',
      logo: '/images/logo.png'
    },
    navigation: {
      courses: [
        { name: 'AI & Machine Learning', href: '/courses/ai-machine-learning', isActive: true, order: 1 },
        { name: 'Data Science', href: '/courses/data-science', isActive: true, order: 2 },
        { name: 'MERN Stack', href: '/courses/complete-mern-stack-development', isActive: true, order: 3 },
        { name: 'Python Programming', href: '/courses/python-programming', isActive: true, order: 4 },
        { name: 'Cloud Computing', href: '/courses/cloud-computing', isActive: true, order: 5 }
      ],
      resources: [
        { name: 'Projects', href: '/projects', isActive: true, order: 1 },
        { name: 'Certificates', href: '/certificates', isActive: true, order: 2 },
        { name: 'Alumni', href: '/alumni', isActive: true, order: 3 },
        { name: 'Blog', href: '/blog', isActive: true, order: 4 },
        { name: 'Resources', href: '/resources', isActive: true, order: 5 }
      ],
      company: [
        { name: 'About Us', href: '/about', isActive: true, order: 1 },
        { name: 'Contact', href: '/contact', isActive: true, order: 2 },
        { name: 'Careers', href: '/careers', isActive: true, order: 3 },
        { name: 'Admin', href: '/admin/login', isActive: true, order: 4 }
      ]
    },
    socialLinks: [
      { name: 'GitHub', href: 'https://github.com/techspert', icon: 'Github', isActive: true, order: 1 },
      { name: 'Twitter', href: 'https://twitter.com/techspert', icon: 'Twitter', isActive: true, order: 2 },
      { name: 'LinkedIn', href: 'https://linkedin.com/company/techspert', icon: 'Linkedin', isActive: true, order: 3 },
      { name: 'Email', href: 'mailto:contact@techspert.com', icon: 'Mail', isActive: true, order: 4 },
      { name: 'YouTube', href: 'https://youtube.com/techspert', icon: 'Youtube', isActive: true, order: 5 }
    ],
    legal: {
      copyright: 'Techspert. All rights reserved.',
      links: [
        { name: 'Privacy Policy', href: '/privacy', isActive: true, order: 1 },
        { name: 'Terms of Service', href: '/terms', isActive: true, order: 2 },
        { name: 'Cookie Policy', href: '/cookies', isActive: true, order: 3 },
        { name: 'Refund Policy', href: '/refund', isActive: true, order: 4 }
      ]
    },
    isActive: true
  },
  certificates: [
    {
      courseName: 'Complete MERN Stack Development',
      studentName: 'John Doe',
      studentEmail: 'john.doe@example.com',
      completionDate: new Date('2024-01-15'),
      course: null, // Will be set to actual course ID
      student: null, // Will be set to actual user ID
      metadata: {
        grade: 'A+',
        score: 95,
        duration: 120,
        skills: ['React', 'Node.js', 'MongoDB', 'Express.js']
      }
    },
    {
      courseName: 'AI & Machine Learning Fundamentals',
      studentName: 'Jane Smith',
      studentEmail: 'jane.smith@example.com',
      completionDate: new Date('2024-02-20'),
      course: null,
      student: null,
      metadata: {
        grade: 'A',
        score: 88,
        duration: 80,
        skills: ['Python', 'TensorFlow', 'Machine Learning', 'Data Science']
      }
    },
    {
      courseName: 'Data Science with Python',
      studentName: 'Mike Johnson',
      studentEmail: 'mike.johnson@example.com',
      completionDate: new Date('2024-03-10'),
      course: null,
      student: null,
      metadata: {
        grade: 'A-',
        score: 85,
        duration: 100,
        skills: ['Python', 'Pandas', 'NumPy', 'Matplotlib', 'Statistics']
      }
    },
    {
      courseName: 'Cloud Computing & AWS',
      studentName: 'Sarah Wilson',
      studentEmail: 'sarah.wilson@example.com',
      completionDate: new Date('2024-03-25'),
      course: null,
      student: null,
      metadata: {
        grade: 'B+',
        score: 82,
        duration: 90,
        skills: ['AWS', 'Cloud Computing', 'DevOps', 'Docker']
      }
    },
    {
      courseName: 'Python Programming Masterclass',
      studentName: 'David Brown',
      studentEmail: 'david.brown@example.com',
      completionDate: new Date('2024-04-05'),
      course: null,
      student: null,
      metadata: {
        grade: 'A',
        score: 90,
        duration: 60,
        skills: ['Python', 'OOP', 'Algorithms', 'Data Structures']
      }
    }
  ]
}

export default demoData
